version: '2'
services:
  jenkins:
    image: m3hran/jenkins:0.3.0
    container_name: jenkins
    restart: always
    env_file:
      - ./resources/jenkins.env
    volumes:
      - /u/data/jenkins/data:/jenkins
      - /u/data/jenkins/logs:/var/log/jenkins
      - ./resources/jenkins.default:/etc/default/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8080
    network_mode: "bridge"
